using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class bullet_script : MonoBehaviour
{
	public Rigidbody rb;
	public float bullet_speed;
	private float life;

	void Start()
	{
		life = 4;
	}

    // Update is called once per frame
    void FixedUpdate()
    {
		rb.velocity = -transform.up * Time.deltaTime * bullet_speed;
		life = life - (1 * Time.deltaTime);
		if ( life < 0 )
		{
			Destroy( gameObject );
			Debug.Log( "timeout" );
		}
    }

	void OnTriggerEnter( Collider other )
	{
		if ( other.tag != "bullet" && other.tag != "gun" && other.tag != "Player" )
		{
			Debug.Log( "bullet hit " + other.tag);
			Destroy( gameObject );
		}
	}
}
